# This is the configuration file for CCU.
# However, CCU uses a "convention over configuration" philosophy, so this 
# file is little used.  Right now it only supports two options.
#
# If running in containers, the host_ip configuration item is required.
# All other configuration items are optional.
# 
# debug: defaults to false.  If set to true, then the CCU integration library 
#     prints out debugging information.
# ip: defaults to 127.0.0.1.  This will work fine when running programs on a 
#     host machine, but it will not work for contaienrs.  So the copy of this
#     file in your sandbox directory must contain the IP address of your host
#     machine as seen by the containers.  172.20.32.1 is my machine, so it surely 
#     will not work for you.  12.0.0.1 will not either (it is the container loop
#     back, not the host loop back).
#
#     More information on Host IP is in the IP Addresses section of the
#     ReferenceDocumentation.
#
debug: true
host_ip: 192.168.1.57